apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
    labels:
        io.kompose.service: crudkubernetes-app
    name: crudkubernetes-app
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: crudkubernetes-app
    template:
        metadata:
            annotations:
                kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
                kompose.version: 1.32.0 (765fde254)
            labels:
                io.kompose.network/crudkubernetes-default: "true"
                io.kompose.service: crudkubernetes-app
        spec:
            containers:
                - env:
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                key: DB_HOST
                                name: env
                      - name: DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                key: DB_NAME
                                name: env
                      - name: DB_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: DB_PASSWORD
                                name: env
                      - name: DB_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                key: DB_USERNAME
                                name: env
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_DATABASE
                                name: env
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_PASSWORD
                                name: env
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_ROOT_PASSWORD
                                name: env
                      - name: MYSQL_USER
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_USER
                                name: env
                  image: mleviking/crudkubernetes:latest  # Mise à jour avec le nom complet de l'image
                  name: crudkubernetes-app
                  ports:
                      - containerPort: 8089
                        protocol: TCP
            restartPolicy: Always
            imagePullSecrets:  # Ajout de la section imagePullSecrets
                - name: regcred
