apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-crudkubernetes-db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-crudkubernetes-db
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: mysql-crudkubernetes-db
        spec:
            containers:
                - env:
                      - name: MYSQL_DATABASE
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_DATABASE
                                name: env
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_PASSWORD
                                name: env
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_ROOT_PASSWORD
                                name: env
                      - name: MYSQL_USER
                        valueFrom:
                            configMapKeyRef:
                                key: MYSQL_USER
                                name: env
                  image: mysql:8.0
                  livenessProbe:
                      exec:
                          command:
                              - mysqladmin
                              - ping
                              - -h
                              - localhost
                              - -u
                              - "${MYSQL_USER}"
                              - --password=${MYSQL_PASSWORD}
                      failureThreshold: 5
                      periodSeconds: 10
                      timeoutSeconds: 5
                  name: container-mysql-crudkubernetes
                  ports:
                      - containerPort: 3306
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /var/lib/mysql
                        name: mysql-data
            restartPolicy: Always
            volumes:
                - name: mysql-data
                  persistentVolumeClaim:
                      claimName: mysql-data
