apiVersion: v1
kind: Service
metadata:
    name: mysql-crudkubernetes-db
spec:
    ports:
        - name: "3306"
          port: 3306
          targetPort: 3306
    selector:
        app: mysql-crudkubernetes-db
