apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-crudkubernetes-db
spec:
    ports:
        - name: "8086"
          port: 8086
          targetPort: 80
    selector:
        app: phpmyadmin-crudkubernetes-db
