apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: phpmyadmin-crudkubernetes-db
  name: phpmyadmin-crudkubernetes-db
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin-crudkubernetes-db
