apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: phpmyadmin-crudkubernetes-db
  name: phpmyadmin-crudkubernetes-db
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin-crudkubernetes-db
