apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: phpmyadmin-crudkubernetes-db
  name: phpmyadmin-crudkubernetes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin-crudkubernetes-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/crudkubernetes-default: "true"
        io.kompose.service: phpmyadmin-crudkubernetes-db
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: env
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: env
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: env
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env
            - name: PMA_HOST
              value: mysql-crudkubernetes-db
            - name: PMA_PASSWORD
            - name: PMA_USER
          image: phpmyadmin/phpmyadmin:latest
          name: container-phpmyadmin-crudkubernetes
          ports:
            - containerPort: 80
              hostPort: 8086
              protocol: TCP
      restartPolicy: Always
