apiVersion: v1
kind: Service
metadata:
    name: crudkubernetes-app
spec:
    type: LoadBalancer
    ports:
        - name: "8089"
          port: 8089
          targetPort: 8089
    selector:
        app: crudkubernetes-app
