apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: crudkubernetes-app
    name: crudkubernetes-app
spec:
    type: LoadBalancer  # Modification ici pour utiliser un LoadBalancer
    ports:
        - name: "8089"
          port: 8089
          targetPort: 8089
    selector:
        io.kompose.service: crudkubernetes-app
