server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:crudkubernetesdb}?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:user}
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-crudkubernetes
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

spring-doc:
  api-docs:
    path: /api-docs

info:
  application:
    name: crudkubernetes
    version: '@project.version@'
